<a href="https://colab.research.google.com/github/jeenu-chacko/Python-Basics/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

1.18.5


In [8]:
a=np.array([[1,2,3,4],[5,6,7]])
print(a)

[list([1, 2, 3, 4]) list([5, 6, 7])]


In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('int64')

In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [122]:
arr = np.array([1, 2, 3, 4])
print(arr.reshape(2,2))

[[1 2]
 [3 4]]


In [79]:
arr1 =np.array([1,2,3,4,5])
print(arr1[0])
print("*******")
arr2 =np.array([[1,2,3,4,5],[6,7,8,9]])
print(arr2[0])
print("*******")
arr3 = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19]]])
print(arr3[0])
print("*******")
print(arr3[0][0])
print("*******")
print(arr3[0,0][3])


1
*******
[1, 2, 3, 4, 5]
*******
[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9, 10])]
*******
[1, 2, 3, 4, 5]
*******
4


In [92]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1[2:])
print("*******")
print(arr[-3:-1])
print("*******")
print(arr[1:5:2])
print("*******")
print(arr[::2])


[3 4 5 6 7]
*******
[5 6]
*******
[2 4]
*******
[1 3 5 7]


In [100]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print("*******")
print(arr[1])
print("*******")
print(arr[1][1:])
print(arr[1,1:])
print("*******")
print(arr[0:2, 2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
*******
[ 6  7  8  9 10]
*******
[ 7  8  9 10]
[ 7  8  9 10]
*******
[3 8]


In [107]:
#Change data type from float to integer by using int as parameter value:

a=np.array([1,2,3,4])
print(a.dtype)
print("*******")
a=np.array([1,2,3,4]).astype(float)
print(a.dtype)
print("*******")

int64
*******
float64
*******


In [108]:
arr = np.array([[1, 2, 3, 4,5], [7,5, 6, 7, 8]])
n,l=arr.shape
print(n*l)

10


In [110]:
arr=np.array([7,2,3,1,9])
print(np.sort(arr))

[1 2 3 7 9]


In [115]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)
for x in x:
  print(arr[x])
x = np.where(arr%2 == 0)
print(x)

(array([3, 5, 6]),)
[4 4 4]
(array([1, 3, 5, 6]),)
